/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as UsernameRouteRouteImport } from './routes/$username/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBookingIdRouteImport } from '../routes/app/$bookingId/reschedule.tsx
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as AppBookingIdRescheduleRouteImport } from './routes/app/$bookingId_.reschedule.tsx'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRouteRoute = UsernameRouteRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBookingIdRoute = AppBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookingIdRescheduleRoute = AppBookingIdRescheduleRouteImport.update({
  id: '/reschedule',
  path: '/reschedule',
  getParentRoute: () => AppBookingIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$bookingId': typeof AppBookingIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$bookingId/reschedule': typeof AppBookingIdRescheduleRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteRoute
  '/app/$bookingId': typeof AppBookingIdRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/$bookingId/reschedule': typeof AppBookingIdRescheduleRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/$bookingId': typeof AppBookingIdRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/$bookingId/reschedule': typeof AppBookingIdRescheduleRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/app'
    | '/app/$bookingId'
    | '/app/'
    | '/app/$bookingId/reschedule'
    | '/login'
    | '/register'
    | '/app/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/app/$bookingId'
    | '/app'
    | '/app/$bookingId/reschedule'
    | '/login'
    | '/register'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/app'
    | '/app/$bookingId'
    | '/app/'
    | '/app/$bookingId/reschedule'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRouteRoute: typeof UsernameRouteRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$bookingId': {
      id: '/app/$bookingId'
      path: '/$bookingId'
      fullPath: '/app/$bookingId'
      preLoaderRoute: typeof AppBookingIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$bookingId/reschedule': {
      id: '/app/$bookingId/reschedule'
      path: '/reschedule'
      fullPath: '/app/$bookingId/reschedule'
      preLoaderRoute: typeof AppBookingIdRescheduleRouteImport
      parentRoute: typeof AppBookingIdRoute
    }
  }
}

interface AppBookingIdRouteChildren {
  AppBookingIdRescheduleRoute: typeof AppBookingIdRescheduleRoute
}

const AppBookingIdRouteChildren: AppBookingIdRouteChildren = {
  AppBookingIdRescheduleRoute: AppBookingIdRescheduleRoute,
}

const AppBookingIdRouteWithChildren = AppBookingIdRoute._addFileChildren(
  AppBookingIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppBookingIdRoute: typeof AppBookingIdRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBookingIdRoute: AppBookingIdRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRouteRoute: UsernameRouteRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
